version: '2.0'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - "db"
    command: ["./wait-for-postgres.sh", "sms_db:5432", "--", "flask", "run", "--host", "0.0.0.0", "--port", "5000"]
  db:
    image: postgres
